### ISSUE TITLE
Questions for Bhin2vec

### ISSUE THREAD

**Issue by CJNabla** [sh0416/BHIN2VEC#1]
I want to get some sample data to implement experiments. Thanks for your help

**Comment by sh0416** [comment]
Link:

https://drive.google.com/drive/folders/1fUQWiMsk7kzv2bYat3P8Id52hDnU71Iy?usp=sharing

I just found the preprocessed data. Maybe the one thing to be guaranteed in the data is that for every node, at least one node per each type.

Thanks,

**Comment by CJNabla** [comment]
I received the data. Thanks for your help.
